### ISSUE TITLE
Transparent Background?

### ISSUE THREAD

**Issue by xsorifc28** [Cherry/placeholders.dev#37]
Is it possible to have a transparent background?
I have tried:
```
https://images.placeholders.dev/?width=1055&height=100&text=Made%20with%20placeholders.dev&bgColor=%23rgba(0,0,0,0)&textColor=%23ff0000
```
(both encoded & not)

The transparent text example from read me also does not work:
```
https://images.placeholders.dev/?width=200&amp;height=100&amp;bgColor=%23000&amp;textColor=rgba(255,0,0,1)
```

**Comment by Cherry** [comment]
Thanks for the issue!

```
https://images.placeholders.dev/?width=1055&height=100&text=Made%20with%20placeholders.dev&bgColor=rgba(0,0,0,0)&textColor=rgba(255,255,255,1)
```

Or encoded:

```
https://images.placeholders.dev/?width=1055&height=100&text=Made%20with%20placeholders.dev&bgColor=rgba(0%2C0%2C0%2C0)&textColor=rgba(255%2C255%2C255%2C1)
```

This works fine for me. If I throw it onto a black background, it's visible.

The issue in your example is likely the `bgColor=%23rgba`. `%23` is an `#` which is only usable with hex colors, so you're actually sending `#rgba(...)` which is invalid.

**Comment by xsorifc28** [comment]
Thanks, apologies for the typo there. When I copied the readme example the url had "&amp;" which broke the parsing. All good!
