### ISSUE TITLE
Add paragraph breaks support

### ISSUE THREAD

**Issue by Romybron** [Cherry/placeholders.dev#7]
Adding (automatic) paragraph breaks support that would allow the text to always stay within the frame

### Examples

**Initial placeholder**: 
/?width=250&height=200&text=This%20text%20is%20%20too%20long&bgColor=%23f7f6f6
![image](https://user-images.githubusercontent.com/66818801/105036224-803e7500-5a5c-11eb-867a-b561bb623993.png)

**Using an automatic paragraph break**:
/?width=250&height=200&text=This%20text%20is%20%20too%20long **&break=auto** &bgColor=%23f7f6f6
![image](https://user-images.githubusercontent.com/66818801/105036138-60a74c80-5a5c-11eb-9fe3-1b3d6dace04c.png)

**Using a manual paragraph break**:
/?width=250&height=200&text=This%20text **&break** &text=is%20too%20long&bgColor=%23f7f6f6
![image](https://user-images.githubusercontent.com/66818801/105036703-25f1e400-5a5d-11eb-857c-396fa1f5b85d.png)

**Using both together**:
/?width=250&height=200&text=This%20text%20is%20too **&break** &text=long **&break=auto** &bgColor=%23f7f6f6
![image](https://user-images.githubusercontent.com/66818801/105036982-93057980-5a5d-11eb-8da3-0f9ee690eee8.png)

That would add a nice addition to the already useful Placeholders!

**Comment by adamus1red** [comment]
IMO even just allowing people to use %0A (url-encoded new line) in their text string would provide an east work around rather than having to workout if the text is going to run off the image.

**Comment by Cherry** [comment]
Thanks for the issue! I've implemented this now using `textWrap` as a URL option:

`https://images.placeholders.dev/?width=350&height=200&text=Some%20very%20long%20and%20wrapped%20string&bgColor=%23f7f6f6&textWrap=true`

![](https://images.placeholders.dev/?width=350&height=200&text=Some%20very%20long%20and%20wrapped%20string&bgColor=%23f7f6f6&textWrap=true)

vs without wrapping:

`https://images.placeholders.dev/?width=350&height=200&text=Some%20very%20long%20and%20wrapped%20string&bgColor=%23f7f6f6`

![](https://images.placeholders.dev/?width=350&height=200&text=Some%20very%20long%20and%20wrapped%20string&bgColor=%23f7f6f6)
